services:
  keycloak:
    image: keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/sample
    volumes:
      - ./config:/opt/keycloak/data/import/:ro
    command: 
      - start-dev
      - --import-realm
    ports:
      - '8080:8080'

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2

  broker-1:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker-1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_OFFSETS_COMMIT_REQUIRED_ACKS: -1
      KAFKA_ACKS: -1
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: broker-1
    depends_on:
      - zookeeper

  broker-2:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker-2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_OFFSETS_COMMIT_REQUIRED_ACKS: -1
      KAFKA_ACKS: -1
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: broker-2
    depends_on:
      - zookeeper

  broker-3:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker-3:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_OFFSETS_COMMIT_REQUIRED_ACKS: -1
      KAFKA_ACKS: -1
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: broker-3
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    restart: always
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKAUI_CONFIGURATION: |
        logging:
          level:
            com.provectus.kafka.ui.service.rbac: TRACE
            com.provectus.kafka.ui.service.rbac.extractor: TRACE
            org.springframework.security: TRACE
            software.amazon.msk.auth: TRACE
        kafka:
          clusters:
            -
              name: dev
              bootstrapServers: broker-1:9092,broker-2:9092,broker-3:9092
              metrics:
                port: 9997
                type: JMX
        auth:
          type: OAUTH2
          oauth2:
            client:
              keycloak:
                clientId: kafka-ui
                scope: openid
                issuer-uri: http://${DOCKER_HOST_IP:-127.0.0.1}:8080/realms/sample
                user-name-attribute: preferred_username
                client-name: keycloak
                provider: oauth
                custom-params:
                  type: keycloak
                  roles-field: kafka-ui_roles
        rbac:
          roles:
            - name: "role_admin"
              clusters:
                - dev
              subjects:
                - provider: oauth
                  type: role
                  value: "role_admin"
              permissions:
                - resource: applicationconfig
                  actions: all
                - resource: clusterconfig
                  actions: all
                - resource: topic
                  value: ".*"
                  actions: all 
                - resource: consumer
                  value: ".*"
                  actions: all
                - resource: schema
                  value: ".*"
                  actions: all
                - resource: connect
                  value: ".*"
                  actions: all
                - resource: ksql
                  value: ".*"
                  actions: all
                - resource: acl
                  value: ".*"
                  actions: all
            - name: "role_all_reader"
              clusters:
                - dev
              subjects:
                - provider: oauth
                  type: role
                  value: "role_all_reader"
              permissions:
                - resource: applicationconfig
                  actions: [ view ] 
                - resource: clusterconfig
                  actions: [ view ] 
                - resource: topic
                  value: ".*"
                  actions: [ view ] 
                - resource: consumer
                  value: ".*"
                  actions: [ view ] 
                - resource: schema
                  value: ".*"
                  actions: [ view ] 
                - resource: connect
                  value: ".*"
                  actions: [ view ] 
                - resource: ksql
                  actions: [ view ] 
                - resource: acl
                  value: ".*"
                  actions: [ view ] 
        
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8081:8080
    entrypoint: >
      /bin/sh -c '
      wget https://repo1.maven.org/maven2/software/amazon/msk/aws-msk-iam-auth/1.1.9/aws-msk-iam-auth-1.1.9.jar -O /home/kafkaui/aws-msk-iam-auth-1.1.9.jar
      && export LOADER_PATH=/home/kafkaui/aws-msk-iam-auth-1.1.9.jar
      && echo -e "$${KAFKAUI_CONFIGURATION}" > /home/kafkaui/config.yml
      && export SPRING_CONFIG_ADDITIONAL_LOCATION=/home/kafkaui/config.yml
      && java --add-opens java.rmi/javax.rmi.ssl=ALL-UNNAMED  $JAVA_OPTS -jar kafka-ui-api.jar
      '
    depends_on:
      - keycloak

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        micronaut:
          security:
            enabled: true
            oauth2:
              enabled: true
              clients:
                keycloak:
                  client-id: "akhq"
                  openid:
                    issuer: "http://${DOCKER_HOST_IP:-127.0.0.1}:8080/realms/sample"
        akhq:
          security:
            default-group: no-roles
            oidc:
              enabled: true
              providers:
                keycloak:
                  label: "Login with Keycloak"
                  username-field: preferred_username
                  groups-field: akhq_roles
                  groups:
                    - name: role_admin
                      groups:
                        - admin
                    - name: role_all_reader
                      groups:
                        - reader
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "broker-1:9092,broker-2:9092,broker-3:9092"
              schema-registry:
                url: "http://schema-registry:8085"
              connect:
                - name: "connect"
                  url: "http://connect:8083"
    ports:
      - 18080:8080
    depends_on:
      - keycloak
