version: '3.4'
x-kafka-enviroment: &kafka-enviroment
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
  KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
  KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  KAFKA_MIN_INSYNC_REPLICAS: 2
  KAFKA_OFFSETS_COMMIT_REQUIRED_ACKS: -1
  KAFKA_ACKS: -1
  KAFKA_LOG4J_ROOT_LOGLEVEL: INFO

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_ADMIN_ENABLE_SERVER: true  # 管理者用WebGUIサーバーを起動
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2

  broker-1:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9092:9092'
    environment:
      <<: *kafka-enviroment
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker-1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
    depends_on:
      - zookeeper

  broker-2:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9093:9093'
    environment:
      <<: *kafka-enviroment
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker-2:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
    depends_on:
      - zookeeper

  broker-3:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9094:9094'
    environment:
      <<: *kafka-enviroment
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker-3:19094,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
    depends_on:
      - zookeeper

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: '{"akhq": {"connections": {"docker-kafka-server": {"schema-registry": {"url": "http://schema-registry:8085"}, "properties": {"bootstrap.servers": "broker-1:19092,broker-2:19093,broker-3:19094"}, "connect": [{"url": "http://connect:8083", "name": "connect"}]}}}}'
    ports:
      - 8080:8080
    links:
      - broker-1
      - broker-2
      - broker-3


